### ISSUE TITLE
Lists and reports?

### ISSUE THREAD

**Issue by tmikaeld** [dlin-me/saasu#3]
Hello again,

I noticed now that lists and reports are not in this API Client.

I could spend the time figuring out how to add this to you project, but that would probably take hours and i don't want to mess up anything.

I'm referring to this in the API Documentation: http://help.saasu.com/api/#toc-http-get

I specifically needed to get FullInventoryItemList.

**Comment by tmikaeld** [comment]
I could use Criteria and search for all item's that are active, this returns the same as FullInventoryItemList, but it is of course slower.

**Comment by dlin-me** [comment]
Hi, thanks again for you input.

The 'Search' function is just the 'List' function with a different name. It makes use of the 'list' api.
'Reports' is not supported. Saasu only provide one report service. I will wait for more service become available before covering 'Report' part.

I will update the Readme file with all your input. Thanks

**Comment by tmikaeld** [comment]
Ah, ok.

How do i get the list without adding any filtering?
Because as soon as i add a filter, the retrieve of items is much slower.

**Comment by dlin-me** [comment]
Hi, I've updated the README, please have a read for details. Basically a Criteria object tells the API what to list and what filters apply. You can simply pass a empty Criteria object with no properties if you don't want to apply any filter.

I've also got a new release that replaces the deprecated InventoryItemList and ComboItemList with FullInventoryItemList and FullComboItemList calls. Because Saasu is dropping the support for the two old list api in Oct.

Cheers.

**Comment by tmikaeld** [comment]
Superb!

Thank you for all the help and for the fixes - looking through your code is a joy, it's all very well made!
